# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate euclidean distance between two vectors
#'
#' @param ptr1 Rcpp::XPtr of recording object 1
#' @param ptr2 Rcpp::Xptr of recording object 2
#' @param index1 start index for ptr1 (R notation)
#' @param index2 start index for ptr2 (R notation)
#' @param length total length to calculate
#'
#' @return A numeric vector of length one
#' @export
dist <- function(ptr1, ptr2, index1, index2, length) {
    .Call('accr_dist', PACKAGE = 'accr', ptr1, ptr2, index1, index2, length)
}

